services:
  - type: web
    name: t3v-server
    env: go
    buildCommand: go build -tags netgo -ldflags="-s -w" -o app
    startCommand: ./app
    envVars:
      - key: GO_VERSION
        value: 1.25.5